#!/bin/bash

# Definición de colores
RESET="\033[0m"
BOLD="\033[1m"
BLACK="${BOLD}\033[30m"
WHITE="${BOLD}\033[37m"
RED="${BOLD}\033[31m"
RED_LITE="\033[31m"
BLUE="${BOLD}\033[34m"
BLUE_LITE="\033[34m"
CYAN="${BOLD}\033[36m"
CYAN_LITE="\033[36m"
GREEN="${BOLD}\033[32m"
GREEN_LITE="\033[32m"
MAGENTA="${BOLD}\033[35m"
MAGENTA_LITE="\033[35m"
YELLOW="${BOLD}\033[33m"
YELLOW_LITE="\033[33m"
CY_CUSTOM="${BOLD}\033[38;2;23;147;209m"

# Comprobar e instalar proot si no existe
if ! command -v proot &> /dev/null; then
    sleep 0.5
    echo -e "\n${GREEN_LITE}[${WHITE}*${GREEN_LITE}]${RESET} Instalando proot..."
    pkg install proot -y &> /dev/null
    sleep 0.5
fi

# Función para manejar Ctrl+C
function Adios() {
    echo
    printf "${BLUE}[${WHITE}+${BLUE}]${WHITE} Creador: ${YELLOW}Lizandro YT\n"
    printf "${BLUE}[${WHITE}+${BLUE}]${WHITE} Herramienta: ${YELLOW}GhostRoot\n"
    printf "${BLUE}[${WHITE}+${BLUE}]${WHITE} GitHub: ${YELLOW}https://github.com/LizandroYT\n"
    echo
    exit
}
trap Adios INT

# Banner ASCII
function banner1() {
    clear
    sleep 0.5
    printf "${BLACK}"
    cat <<'EOF'
                      :::!~!!!!!:.
                  .xUHWH!! !!?M88WHX:.
                .X*#M@$!!  !X!M$$$$$$WWx:.
               :!!!!!!?H! :!$!$$$$$$$$$$8X:
              !!~  ~:~!! :~!$!#$$$$$$$$$$8X:
             :!~::!H!<   ~.U$X!?R$$$$$$$$MM!
             ~!~!!!!~~ .:XW$$$U!!?$$$$$$RMM!
               !:~~~ .:!M"T#$$$$WX??#MRRMMM!
               ~?WuxiW*`   `"#$$$$8!!!!??!!!
             :X- M$$$$  *   `"T#$T~!8$WUXU~
            :%`  ~#$$$m:        ~!~ ?$$$$$$
          :!`.-   ~T$$$$8xx.  .xWW- ~""##*""
.....   -~~:<` !    ~?T#$$@@W@*?$$    /`
W$@@M!!! .!~~ !!     .:XUW$W!~ `"~:    :
#"~~`.:x%`!!  !H:   !WM$$$$Ti.: .!WUn+!`
:::~:!!`:X~ .: ?H.!u "$$$B$$$!W:U!T$$M~
.~~   :X@!.-~   ?@WTWo("*$$$W$TH$! `
Wi.~!X$?!-~    : ?$$$B$Wu("**$RM!
$R@i.~~ !     :   ~$$$$$B$$en:``
?MXT@Wx.~    :     ~"##*$$$$M~
EOF
    sleep 0.9
    printf "${BLUE}[${WHITE}+${BLUE}]${WHITE} Creador: ${YELLOW}Lizandro YT\n"
    sleep 0.4
    printf "${BLUE}[${WHITE}+${BLUE}]${WHITE} Herramienta: ${YELLOW}GhostRoot\n"
    sleep 0.4
    printf "${BLUE}[${WHITE}+${BLUE}]${WHITE} GitHub: ${YELLOW}https://github.com/LizandroYT\n"
    sleep 4
}

banner1

echo -e "${BLACK}Comenzando Proceso Root .."
sleep 2

RUTA="$PREFIX/bin"
ROOT_FILE="$RUTA/root"

# Eliminar root anterior si existe
[ -e "$ROOT_FILE" ] && rm -f "$ROOT_FILE"

# Crear y configurar el nuevo archivo root
echo "proot -0 -w ~ $PREFIX/bin/bash" > "$ROOT_FILE"
chmod 700 "$ROOT_FILE"

echo
sleep 4
clear

echo -e "${GREEN}"
cat <<'EOF'
 ________
< GhostRoot >
 --------
        \   ^__^
         \  (xx)\_______
            (__)\       )\/\
             U  ||----w||
                ||     ||
EOF
echo -e "${RESET}"

for msg in \
    "Proceso:    Finalizado" \
    "Creador:    Lizandro YT" \
    "Herramienta: GhostRoot" \
    "GitHub:     https://github.com/LizandroYT" \
    "Activacion: Para Activar Root Utiliza La Palabra${RED} root${RESET}"
do
    printf "${BLUE}[${WHITE}+${BLUE}]${WHITE} %s\n" "$msg"
    sleep 0.3
done
echo
